title: CAIO
description: Cityâ€“AI Coevolution
theme: minima

url: "https://jonpappalord.github.io"
baseurl: "/caio"

header_pages:
  - about.md
  - people.md
  - research.md
  - publications.md
  - news.md
  - contact.md
